# 공통 설정
spring:
  profiles:
    include:
      - oauth
      - s3

---
# 로컬 환경 설정
server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database: mysql

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    user: root
    password: 

logging:
  level:
    org.hibernate.type.descriptor.sql: trace


jwt:
  secret: test

---
# 프로덕션(배포) 환경 설정

server:
  port: 8081

spring:
  config:
    activate:
      on-profile: test1

  datasource:
    url: ${DATABASE_URL}
    driver-class-name: com.mysql.jdbc.Driver
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  jpa:
    database: mysql
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql : false
        format_sql : false

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    user: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

jwt:
  secret: ${JWT_SECRET}

---
server:
  port: 8082

spring:
  config:
    activate:
      on-profile: test2

  datasource:
    url: ${DATABASE_URL}
    driver-class-name: com.mysql.jdbc.Driver
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  jpa:
    database: mysql
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql : false
        format_sql : false

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    user: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

jwt:
  secret: ${JWT_SECRET}