# 공통 설정
server:
  port: 8080

---
# 로컬 환경 설정
spring:
  profiles:
    active: local
    include: oauth

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    org.hibernate.type.descriptor.sql: trace
jwt:
  secret: test

---
# 프로덕션(배포) 환경 설정
spring:
  profiles:
    active: prov
    include: oauth

  datasource:
    url: ${DATABASE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  jpa:
    database: mysql
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql : false
        format_sql : false
