# 공통 설정
spring:
  profiles:
    include:
      - oauth
      - s3
      - mysql

---
# 로컬 환경 설정
server:
  port: 8080

s3:
  base-path: hdu

spring:
  config:
    activate:
      on-profile: local

  redis:
    host: localhost
    port: 6379


#  datasource:
#    url: jdbc:mysql://localhost:3306/test
#    driver-class-name: com.mysql.jdbc.Driver
#    username: LeeJerry
#    password: LeeJerry

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
#    user: LeeJerry
#    password: LeeJerry

logging:
  level:
    org.hibernate.type.descriptor.sql: trace


jwt:
  secret: test

#---
## 프로덕션(배포) 환경 설정
#
#server:
#  port: 8081
#
#spring:
#  config:
#    activate:
#      on-profile: test1
#
#  datasource:
#    url: ${database_url}
#    driver-class-name: com.mysql.jdbc.driver
#    username: ${database_user}
#    password: ${database_password}
#
#  jpa:
#    database: mysql
#    open-in-view: false
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        show_sql : false
#        format_sql : false
#
#  flyway:
#    enabled: false
#    baseline-on-migrate: true
#    baseline-version: 0
#    user: ${database_user}
#    password: ${database_password}
#
#jwt:
#  secret: ${jwt_secret}
#
#---
#server:
#  port: 8082
#
#spring:
#  config:
#    activate:
#      on-profile: test2
#
#  datasource:
#    url: ${database_url}
#    driver-class-name: com.mysql.jdbc.driver
#    username: ${database_user}
#    password: ${database_password}
#
#  jpa:
#    database: mysql
#    open-in-view: false
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        show_sql : false
#        format_sql : false
#
#  flyway:
#    enabled: false
#    baseline-on-migrate: true
#    baseline-version: 0
#    user: ${database_user}
#    password: ${database_password}
#
#jwt:
#  secret: ${jwt_secret}
