# 공통 설정
server:
  port: 8080

spring:
  profiles:
    include:
      - oauth
      - s3
      - flyway

---
# 로컬 환경 설정
spring:
  config:
    activate:
      on-profile: local

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    user: sa
    password:
    locations:
      - classpath:db/migration
      - classpath:db/seed

logging:
  level:
    org.hibernate.type.descriptor.sql: trace


jwt:
  secret: test
---
# 프로덕션(배포) 환경 설정
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DATABASE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  jpa:
    database: mysql
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql : false
        format_sql : false

  flyway:
    enabled: true
    baseline-on-migrate: true
    user: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    locations:
      - classpath:db/migration
      - classpath:db/seed
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: ${JWT_SECRET}
