name: Java CI / CD

env:
  S3_BUCKET_NAME: hanghae7e-backend

on:
  push:
    branches: [ "main", "CICD-Setting" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'


    - name: Grant excute permission for gradlew
      run: chmod +x gradlew

    - name: Test and Build with Gradle
      run: ./gradlew build -x test
        
    - name: Make zip file
      run: zip -r ./hanghae7E_BE.zip *
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./hanghae7E_BE.zip s3://$S3_BUCKET_NAME/hanghae7E_BE.zip
